[[permission]]
identifier = "allow-set-recording-overlay-visible"
description = "Enables the set_recording_overlay_visible command without any pre-configured scope."
commands.allow = ["set_recording_overlay_visible"]

[[permission]]
identifier = "deny-set-recording-overlay-visible"
description = "Denies the set_recording_overlay_visible command without any pre-configured scope."
commands.deny = ["set_recording_overlay_visible"]
