/**
 * Constructor subpath for committed historical-schema modules generated by
 * Epicenter. Applications are supported through those generated endpoints,
 * not direct calls to this helper. The explicit subpath marks ownership; it
 * cannot prevent deliberate imports or mismatched generic row types.
 */

export { historicalSchema } from './historical-schema.js';
