/**
 * Render one inert historical schema module from a current workspace
 * definition (ADR-0125).
 *
 * Apps run this at development time, before shipping a schema change: it
 * snapshots the CURRENT schema into a generated `.ts` module that a future
 * migration bundle uses as a source or target. The module is byte-stable by
 * construction: it embeds the canonical descriptor string as the sole truth,
 * derives its hash at load time, carries generated migration cell types, and
 * never calls `defineTable`, so later builder-API changes cannot drift it.
 * The emitted module uses the explicit generated-artifact constructor subpath;
 * the ordinary application barrel does not expose that constructor.
 *
 * Generated row types are cells only (ids are runtime-carried) and honest
 * about what survives generation: instants and datetimes keep their brands,
 * selects keep their member unions, brands on plain string columns are
 * erased, and `field.json` columns become `unknown` for the transform author
 * to narrow.
 */

import type { TableDefinitions, WorkspaceDefinition } from './definition.js';

export function renderHistoricalSchemaModule({
	definition,
	exportName,
}: {
	definition: WorkspaceDefinition<TableDefinitions>;
	/** The generated const name, for example `recordsSchemaV1`. */
	exportName: string;
}): string {
	if (!/^[A-Za-z_$][A-Za-z0-9_$]*$/.test(exportName)) {
		throw new Error(
			`Historical schema export name '${exportName}' is not a valid identifier`,
		);
	}

	const usedBrands = new Set<string>();
	const tableTypes = Object.entries(definition.tables).map(
		([tableName, table]) => {
			const columnTypes = Object.entries(table.compiledColumns)
				.filter(([columnName]) => columnName !== 'id')
				.map(([columnName, column]) => {
					const base = columnTypeText({
						kind: column.kind,
						schema: table.fields[columnName],
						usedBrands,
					});
					const value = column.isNullable ? `${base} | null` : base;
					return `\t\t${propertyKey(columnName)}: ${value};`;
				});
			return `\t${propertyKey(tableName)}: {\n${columnTypes.join('\n')}\n\t};`;
		},
	);

	const brandImport =
		usedBrands.size === 0
			? ''
			: `import type { ${[...usedBrands].sort().join(', ')} } from '@epicenter/field';\n`;

	return `/**
 * Generated by Epicenter from workspace '${definition.id}'.
 * Historical schema ${definition.recordsSchemaHash}.
 * Inert snapshot: do not edit; regenerate instead.
 */

import { historicalSchema } from '@epicenter/workspace/sqlite/generated';
${brandImport}
export const ${exportName} = historicalSchema<{
${tableTypes.join('\n')}
}>(${JSON.stringify(definition.recordsDescriptor)});
`;
}

function columnTypeText({
	kind,
	schema,
	usedBrands,
}: {
	kind: string;
	schema: unknown;
	usedBrands: Set<string>;
}): string {
	switch (kind) {
		case 'boolean':
			return 'boolean';
		case 'integer':
		case 'number':
			return 'number';
		case 'instant':
			usedBrands.add('InstantString');
			return 'InstantString';
		case 'datetime':
			usedBrands.add('DateTimeString');
			return 'DateTimeString';
		case 'select': {
			const members = readEnumMembers(schema);
			return members ?? 'string';
		}
		case 'multiSelect': {
			const members = readEnumMembers(readItems(schema));
			return members === null ? 'string[]' : `(${members})[]`;
		}
		case 'tags':
			return 'string[]';
		case 'json':
			return 'unknown';
		default:
			// string, url, date, reference: brands do not survive generation.
			return 'string';
	}
}

function readEnumMembers(schema: unknown): string | null {
	const atRest: unknown = JSON.parse(JSON.stringify(schema ?? null));
	const inner = readNullableInner(atRest) ?? atRest;
	if (
		typeof inner !== 'object' ||
		inner === null ||
		!Array.isArray((inner as Record<string, unknown>).enum)
	) {
		return null;
	}
	const members = (inner as { enum: unknown[] }).enum;
	if (!members.every((member) => typeof member === 'string')) return null;
	return members.map((member) => JSON.stringify(member)).join(' | ');
}

function readItems(schema: unknown): unknown {
	const atRest: unknown = JSON.parse(JSON.stringify(schema ?? null));
	const inner = readNullableInner(atRest) ?? atRest;
	if (typeof inner !== 'object' || inner === null) return null;
	return (inner as Record<string, unknown>).items ?? null;
}

function readNullableInner(schema: unknown): unknown | null {
	if (typeof schema !== 'object' || schema === null || Array.isArray(schema)) {
		return null;
	}
	const anyOf = (schema as Record<string, unknown>).anyOf;
	if (!Array.isArray(anyOf) || anyOf.length !== 2) return null;
	const nullIndex = anyOf.findIndex(
		(branch) =>
			typeof branch === 'object' &&
			branch !== null &&
			Object.keys(branch).length === 1 &&
			(branch as Record<string, unknown>).type === 'null',
	);
	if (nullIndex === -1) return null;
	return anyOf[nullIndex === 0 ? 1 : 0];
}

function propertyKey(name: string): string {
	return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name) ? name : JSON.stringify(name);
}
