name: Auto-Label Issues with Claude

on:
  issues:
    types: [opened, edited]

jobs:
  auto-label:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      id-token: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      
      - name: Auto-label with Claude
        uses: anthropics/claude-code-action@beta
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          model: claude-3-5-sonnet-20241022
          prompt: |
            Analyze this GitHub issue and apply appropriate labels.
            
            Issue #${{ github.event.issue.number }}:
            Title: ${{ github.event.issue.title }}
            Body: ${{ github.event.issue.body }}
            
            Available labels to choose from (select 1-5 most relevant):
            
            Type (choose ONE):
            - bug: Broken functionality or errors
            - feature-request: New feature suggestions  
            - enhancement: Improvements to existing features
            - documentation: Documentation issues or improvements
            - question: Questions about usage
            
            Priority (choose ONE if applicable):
            - critical: Urgent, breaks core functionality
            - high: Important, affects many users
            - medium: Standard priority
            - low: Nice-to-have improvements
            
            Platform (if specifically mentioned):
            - windows: Windows-specific issues
            - macOS: macOS-specific issues
            - linux: Linux-specific issues
            
            Area (if applicable):
            - ui-web: Web interface issues
            - ui-desktop: Desktop app UI issues
            - backend: API or backend issues
            - transcription: Transcription functionality issues
            - audio: Audio processing issues
            
            Apply the most appropriate labels to issue #${{ github.event.issue.number }} using the GitHub API.
            Then add a brief comment explaining which labels were applied and why.