name: Sync AGENTS.md to CLAUDE.md

on:
  push:
    paths:
      - 'AGENTS.md'
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync-files:
    runs-on: ubuntu-latest
    # Skip if the commit author is github-actions bot to prevent loops
    if: github.actor != 'github-actions[bot]'
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
          fetch-depth: 0  # Full history for better diff analysis
      
      - name: Check if sync is needed
        id: check_changes
        run: |
          # Always sync from AGENTS.md to CLAUDE.md
          echo "source=AGENTS.md" >> $GITHUB_OUTPUT
          echo "target=CLAUDE.md" >> $GITHUB_OUTPUT
          
          # Check if files are different
          if ! diff -q AGENTS.md CLAUDE.md >/dev/null 2>&1; then
            echo "sync_needed=true" >> $GITHUB_OUTPUT
          else
            echo "sync_needed=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Sync AGENTS.md to CLAUDE.md
        if: steps.check_changes.outputs.sync_needed == 'true'
        run: |
          # Copy AGENTS.md to CLAUDE.md
          if [ -f "AGENTS.md" ]; then
            cp "AGENTS.md" "CLAUDE.md"
          else
            echo "Source file AGENTS.md not found!"
            exit 1
          fi
      
      - name: Check for differences after sync
        id: check_diff
        if: steps.check_changes.outputs.sync_needed == 'true'
        run: |
          if git diff --quiet HEAD -- "CLAUDE.md"; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi
      
      - name: Commit and push if changed
        if: steps.check_changes.outputs.sync_needed == 'true' && steps.check_diff.outputs.changed == 'true'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add "CLAUDE.md"
          git commit -m "chore: sync CLAUDE.md with AGENTS.md"
          git push